### ISSUE TITLE
 Could not pass event PaperInventoryMoveItemEvent to FilteringHoppers v1.0.7

### ISSUE THREAD

**Issue by matheeuslima** [Cocolennon/FilteringHoppers#2]
Could not pass event PaperInventoryMoveItemEvent to FilteringHoppers v1.0.7
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4238) ~[?:?]
	at java.base/java.util.Arrays.asList(Arrays.java:4223) ~[?:?]
	at FilteringHoppers-1.0.7.jar/me.cocolennon.filteringhoppers.listeners.InventoryMoveItemListener.inventoryMoveItem(InventoryMoveItemListener.java:36) ~[FilteringHoppers-1.0.7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor562.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-39-aa8d38d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:336) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:261) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:447) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:205) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:148) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:995) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:947) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:969) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:745) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1733) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Cocolennon** [comment]
Reported by someone else on Discord, fixed already and will be available in next update.
